name: '📲 Propose a new sponsored download mirror'
labels: ['get.jenkins.io', 'mirrors.jenkins.io', 'mirror', 'sponsors', 'triage']
description: Propose to host a new mirror for the Jenkins downloads (get.jenkins.io).

body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing to host a new download mirror for the Jenkins project!
        Before hitting the "Create" button, please answer the (required) questions below.

        You can check the page <https://www.jenkins.io/download/mirrors/> if you need more details around the requirements for a mirror.
  - type: input
    id: mirror_http_url
    attributes:
      label: Mirror HTTPS URL
      description: |
        Mirror HTTPS public URL (details at <https://www.jenkins.io/download/mirrors/#an-http-server-to-serve-files-for-the-end-users>):
      placeholder: |
        https://<company.awesome>(/jenkins)
    validations:
      required: true
