name: Issues Similarity Analysis
on:
  issues:
    types: [opened, edited]
jobs:
  similarity-analysis:
    runs-on: ubuntu-latest
    if: github.event.issue.state == 'open'
    steps:
      - name: analysis
        uses: actions-cool/issues-similarity-analysis@0a5ea211e6a178915f0f754968fc94ff845bcb41 # v1
        with:
          filter-threshold: 0.7
          title-excludes: 'bug, jenkins'
          comment-title: "### Take a look at these similar issues to see if there isn't already a response to your problem:"
          comment-body: '${index}. ${similarity} #${number}'
          show-footer: false
          since-days: 730
